version: "3.3"

services:
  app:
    build: .
    depends_on:
      - postgres
      - mongo
    ports:
      - "8888:8888"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bancopostgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
